name: Dockerhub Image CI

on:
  push:
    branches: [ dev ]

jobs:
  release:
    name: Build Docker image and push to DockerHub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Get release version
        run: |
          export COMPAS_VERSION=$(sed -n '/const std::string VERSION_STRING/,/^$/p' ./src/constants.h | sed 's/.*"\(.*\)"[^"]*$/\1/')
          echo "::set-env name=COMPAS_VERSION::$COMPAS_VERSION"
        
      - name: Print version
        run: echo $COMPAS_VERSION
        
      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:$COMPAS_VERSION -t ${{ secrets.DOCKER_REPO }}/compas-ci-dev-2:latest .
        
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_REPO }}/compas-ci-dev-2:$COMPAS_VERSION
          docker push${{ secrets.DOCKER_REPO }}/compas-ci-dev-2:latest
          